---
# Install and configure MQ

- name: Install MQ 
  apt: name=rabbitmq-server state=present update_cache=yes cache_valid_time=86400

# Set rabbitmq guest pw
- rabbitmq_user: user=guest password={{ RABBIT_PASS }} force=yes configure_priv=".*" write_priv=".*" read_priv=".*"