---
#- name: Upgrades and Dist-Upgrades servers
- hosts: all
  sudo: yes

  tasks:
  - name: Update apt
    apt: update_cache=yes

  # Upgrade all packages and reboot
  # - name: Upgrade Packages
  #   apt: upgrade=full

  - name: Dist upgrade
    apt: upgrade=dist

  - name: check if a reboot is required
    shell: "[ -f /var/run/reboot-required ]"
    failed_when: False
    register: reboot_required
    changed_when: reboot_required.rc == 0
    notify: reboot

  handlers:
  - name: reboot
    command: /sbin/reboot