---

# Apply common configuration to all hosts
- hosts: all
  sudo: true
  roles:
  - common

# Configure OpenStack controller
- hosts: controller
  sudo: true
  roles:
  - controller

# Configure OpenStack compute nodes
- hosts: compute
  sudo: true
  roles:
  - compute